jobs:
  - job: 'Clippy'
    pool:
      vmImage: 'ubuntu-18.04'
      container: 'rust:latest'
      steps:
        - script: rustup component add clippy
          displayName: Install Clippy
        - script: cargo clippy --all
          displayName: Run clippy

  # Strategy matrix removed from config for brevity,
  # but one can nest it inside a job
  - job: 'Test'
    strategy:
      matrix:
        stable:
          rustup_toolchain: stable
        beta:
          rustup_toolchain: beta
        nightly:
          rustup_toolchain: nightly
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install rust
      - script: cargo build --all
        displayName: Cargo build
      - script: cargo test --all
        displayName: Cargo test

  - job: 'Build'
    strategy:
      matrix:
        windows-stable:
          imageName: 'vs2017-win2016'
          rustup_toolchain: stable
        mac-stable:
          imageName: 'macos-10.13'
          rustup_toolchain: stable
        linux-stable:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: stable
        linux-beta:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: beta
        linux-nightly:
          imageName: 'ubuntu-16.04'
          rustup_toolchain: nightly

    pool:
      vmImage: $(imageName)

    steps:
      - template: '_build/install-rust.yml'
      - script: cargo build --all
        displayName: Cargo build
      - script: cargo test --all
        displayName: Cargo test
