[project]
authors = "Developer Name"
description = "Your description here."
email = "email@example.com"
package_name = "my_game"
title = "My Game"
url = "http://www.example.com/"
uti = "com.company.mygame"
version = "v1.0"

[build]
# List of patterns to exclude when building. Each item is a regular
# expression, which when matched, will exclude the matched file or
# directory from the build.
ignore_list = [
    # Git
    "^.git.*",

    # Binary files
    ".zip$",
    ".tar.gz$",
    ".love$",
    ".exe$",

    # Boon-specific files and directories
    "Boon.toml",
    "release",
]

# If this is set to true, then the default ignore list will not be
# merged with the project specific ignore list. This allows the
# ignore list to be completely overwritten.
exclude_default_ignore_list = false

