[build]
# Which folders and files to exclude when building. (Anything partially containing these too).
ignore_list = [
    ".git",
    "release",
    "play.bat",
    ".gitattributes",
    "screenshots",
    ".love",
    ".exe"
]

[project]
authors = "Developer Name"
description = "Your description here."
email = "email@example.com"
package_name = "my_game"
title = "My Game"
url = "http://www.example.com/"
uti = "com.company.mygame"
version = "v1.0"
