[package]
name = "boon"
version = "0.1.0"
authors = ["Cameron McHenry <camchenry@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.31"
zip = "0.5.2"
walkdir = "2.1.4"
app_dirs = "1.2.1"
reqwest = "0.9.14"
config = "0.8"
fs_extra = "1.1.0"
regex = "1.0.0"
remove_dir_all = "0.5.1"
glob = "0.2.11"
