[package]
name = "boon"
version = "0.1.0"
authors = ["Cameron McHenry <camchenry@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
zip = "0.5.2"
walkdir = "2.2.7"
app_dirs = "1.2.1"
reqwest = "0.9.15"
config = "0.9.2"
fs_extra = "1.1.0"
regex = "1.1.6"
remove_dir_all = "0.5.1"
glob = "0.3.0"
