# If true, build will not be allowed when DEBUG is true
debug_halt = true

# Which folders and files to exclude when building. (Anything partially containing these too).
ignore_list = [
    ".git",
    "releases",
    "play.bat",
    ".gitattributes",
    "screenshots",
    ".love",
    ".exe"
]
