debug_halt = true # If true, build will not be allowed when DEBUG is true
ignore_list = [".git", "releases", "play.bat", ".gitattributes", "screenshots", ".love", ".exe"] # Which folders and files to exclude when building. (Anything partially containing these too).
