version: 2

jobs:
    test:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run:
                name: Test
                command: rustup run stable cargo test
    build:
        docker:
            - image: circleci/rust:latest

        steps:
            - checkout
            - restore_cache:
                key: project-cache
            - run:
                name: Stable Build
                command: |
                    rustup run stable rustc --version --verbose
                    rustup run stable cargo --version --verbose
                    rustup run stable cargo build
            - save_cache:
                key: project-cache
                paths:
                    - "~/.cargo"
                    - "./target"
